[2023-06-30 03:12:22] (DEBUG) => ConnectionError((<urllib3.connection.HTTPConnection object at 0x7fe38b140ac0>, 'Connection to 221.157.125.36 timed out. (connect timeout=30)')) caused by: ConnectTimeoutError((<urllib3.connection.HTTPConnection object at 0x7fe38b140ac0>, 'Connection to 221.157.125.36 timed out. (connect timeout=30)'))
[2023-06-30 03:12:22] (DEBUG) => 데이터 수집을 정상적으로 완료하였습니다.
[2023-06-30 03:12:22] (DEBUG) => Worker-[1000]가 task-[427023]의 'facebook'(을)를 완료하였습니다.
